# Generated by Django 5.2.17 on 2026-08-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='目的地名称')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='英文标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '目的地',
                'verbose_name_plural': '目的地',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='小楠子爱旅行', max_length=100, verbose_name='品牌名称')),
                ('brand_summary', models.TextField(blank=True, verbose_name='品牌介绍')),
                ('official_account_name', models.CharField(default='小楠子爱旅行俱乐部', max_length=100, verbose_name='公众号名称')),
                ('official_account_guide', models.TextField(blank=True, verbose_name='公众号关注指引')),
                ('service_description', models.TextField(blank=True, verbose_name='服务说明')),
                ('about_us', models.TextField(blank=True, verbose_name='关于我们')),
                ('agreement_text', models.TextField(blank=True, verbose_name='用户协议')),
                ('privacy_text', models.TextField(blank=True, verbose_name='隐私政策')),
                ('filing_number', models.CharField(blank=True, max_length=100, verbose_name='备案号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='产品名称')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='英文标识')),
                ('subtitle', models.CharField(blank=True, max_length=220, verbose_name='简短副标题')),
                ('summary', models.TextField(blank=True, verbose_name='产品简介')),
                ('season', models.CharField(blank=True, max_length=100, verbose_name='航季/季节')),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='行程天数')),
                ('hero_image', models.ImageField(blank=True, upload_to='products/heroes/', verbose_name='封面图')),
                ('vessel', models.CharField(blank=True, max_length=160, verbose_name='船只/核心资源')),
                ('departure_city', models.CharField(blank=True, max_length=100, verbose_name='出发地')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('highlights', models.JSONField(blank=True, default=list, verbose_name='产品亮点')),
                ('included', models.JSONField(blank=True, default=list, verbose_name='费用包含')),
                ('excluded', models.JSONField(blank=True, default=list, verbose_name='费用不含')),
                ('suitable_for', models.JSONField(blank=True, default=list, verbose_name='适合人群')),
                ('notices', models.JSONField(blank=True, default=list, verbose_name='重要提醒')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '待审核'), ('published', '已发布'), ('archived', '已下架')], default='draft', max_length=16, verbose_name='发布状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.destination', verbose_name='目的地')),
            ],
            options={
                'verbose_name': '旅行产品',
                'verbose_name_plural': '旅行产品',
                'ordering': ['sort_order', '-published_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(verbose_name='第几天')),
                ('title', models.CharField(max_length=180, verbose_name='行程标题')),
                ('description', models.TextField(verbose_name='行程内容')),
                ('accommodation', models.CharField(blank=True, max_length=160, verbose_name='住宿')),
                ('meals', models.CharField(blank=True, max_length=120, verbose_name='餐食')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='catalog.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '每日行程',
                'verbose_name_plural': '每日行程',
                'ordering': ['sort_order', 'day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='出发日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('label', models.CharField(blank=True, max_length=160, verbose_name='团期说明')),
                ('consultation_status', models.CharField(default='可咨询', max_length=80, verbose_name='咨询状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='catalog.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '出发团期',
                'verbose_name_plural': '出发团期',
                'ordering': ['sort_order', 'start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='图片')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='图片说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
