# Generated by Django 5.2.17 on 2026-08-13 09:32

import catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(blank=True, storage=catalog.storage.build_media_storage, upload_to='products/heroes/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=catalog.storage.build_media_storage, upload_to='products/gallery/', verbose_name='图片'),
        ),
    ]
