# Generated by Django 5.2.17 on 2026-08-14 04:51

import catalog.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_hero_image_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='专题名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='英文标识')),
                ('summary', models.TextField(blank=True, verbose_name='专题简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '内容专题',
                'verbose_name_plural': '内容专题',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='英文标识')),
                ('name', models.CharField(max_length=120, verbose_name='中文名称')),
                ('official_name', models.CharField(blank=True, max_length=160, verbose_name='官方名称')),
                ('summary', models.TextField(blank=True, verbose_name='中文简介')),
                ('hero_image', models.ImageField(blank=True, storage=catalog.storage.build_media_storage, upload_to='vessels/heroes/', verbose_name='封面图')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='载客人数')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='建造年份')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='体验特色')),
                ('source_url', models.URLField(blank=True, verbose_name='官方来源')),
                ('source_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='抓取时间')),
                ('review_status', models.CharField(default='pending', max_length=32, verbose_name='复核状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '船只',
                'verbose_name_plural': '船只',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='source_range',
            field=models.CharField(blank=True, max_length=32, verbose_name='官方行程区间'),
        ),
        migrations.CreateModel(
            name='EditorialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catalog.editorialcollection')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorial_entries', to='catalog.product')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorial_entries', to='catalog.vessel')),
            ],
            options={
                'verbose_name': '专题内容',
                'verbose_name_plural': '专题内容',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CabinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='舱型名称')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='舱型分类')),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='面积（平方米）')),
                ('bed_layout', models.CharField(blank=True, max_length=160, verbose_name='床型')),
                ('view_type', models.CharField(blank=True, max_length=120, verbose_name='窗景/阳台')),
                ('summary', models.TextField(blank=True, verbose_name='中文简介')),
                ('highlights', models.JSONField(blank=True, default=list, verbose_name='舱型亮点')),
                ('image', models.ImageField(blank=True, storage=catalog.storage.build_media_storage, upload_to='vessels/cabins/', verbose_name='图片')),
                ('source_url', models.URLField(blank=True, verbose_name='官方来源')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='catalog.vessel')),
            ],
            options={
                'verbose_name': '舱位类型',
                'verbose_name_plural': '舱位类型',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='departure',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='catalog.vessel', verbose_name='执行船只'),
        ),
        migrations.AddField(
            model_name='product',
            name='vessels',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.vessel'),
        ),
    ]
