# Generated by Django 5.2.17 on 2026-08-15 03:16

import catalog.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def publish_existing_vessels(apps, schema_editor):
    Vessel = apps.get_model("catalog", "Vessel")
    Vessel.objects.filter(is_active=True).update(
        content_status="published",
        published_at=django.utils.timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_editorialcollection_vessel_itineraryday_source_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabintype',
            name='amenities',
            field=models.JSONField(blank=True, default=list, verbose_name='设施'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='deck',
            field=models.CharField(blank=True, max_length=120, verbose_name='甲板'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='英文原文介绍'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='中文完整介绍'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='display_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='展示标签'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='is_accessible',
            field=models.BooleanField(default=False, verbose_name='无障碍舱位'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='展示'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='max_guests',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最多入住人数'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='official_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='官方舱位代码'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='official_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='官方舱位名称'),
        ),
        migrations.AddField(
            model_name='cabintype',
            name='source_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='资料核对时间'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='content_status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='内容发布状态'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='intro_en',
            field=models.TextField(blank=True, verbose_name='英文原文介绍'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='intro_zh',
            field=models.TextField(blank=True, verbose_name='中文完整介绍'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='operator_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容发布时间'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='ship_type',
            field=models.CharField(blank=True, max_length=160, verbose_name='船型定位'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='short_pitch',
            field=models.CharField(blank=True, max_length=220, verbose_name='首页一句话卖点'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='source_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='资料核对时间'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='year_refurbished',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='翻新年份'),
        ),
        migrations.CreateModel(
            name='VesselExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=80, verbose_name='模块类型')),
                ('title_zh', models.CharField(max_length=160, verbose_name='中文标题')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='英文标题')),
                ('body_zh', models.TextField(blank=True, verbose_name='中文内容')),
                ('body_en', models.TextField(blank=True, verbose_name='英文原文')),
                ('is_visible', models.BooleanField(default=True, verbose_name='展示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('source_url', models.URLField(blank=True, verbose_name='官方来源')),
                ('source_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='资料核对时间')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='catalog.vessel', verbose_name='船只')),
            ],
            options={
                'verbose_name': '船上体验模块',
                'verbose_name_plural': '船上体验模块',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VesselMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=catalog.storage.build_media_storage, upload_to='vessels/gallery/', verbose_name='图片')),
                ('alt_zh', models.CharField(blank=True, max_length=180, verbose_name='中文图片说明')),
                ('alt_en', models.CharField(blank=True, max_length=180, verbose_name='英文图片说明')),
                ('source_url', models.URLField(blank=True, verbose_name='图片来源')),
                ('source_note', models.CharField(blank=True, max_length=240, verbose_name='原始说明')),
                ('usage_note', models.CharField(blank=True, max_length=240, verbose_name='使用备注')),
                ('source_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='资料核对时间')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('cabin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.cabintype', verbose_name='舱位')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.vesselexperience', verbose_name='船上体验模块')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.vessel', verbose_name='船只')),
            ],
            options={
                'verbose_name': '船只媒体资源',
                'verbose_name_plural': '船只媒体资源',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CabinDisplayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, verbose_name='分组标识')),
                ('title_zh', models.CharField(max_length=120, verbose_name='中文分组名称')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='英文分组名称')),
                ('is_visible', models.BooleanField(default=True, verbose_name='展示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('cabins', models.ManyToManyField(blank=True, related_name='display_groups', to='catalog.cabintype')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_groups', to='catalog.vessel', verbose_name='船只')),
            ],
            options={
                'verbose_name': '舱位展示分组',
                'verbose_name_plural': '舱位展示分组',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('vessel', 'slug'), name='unique_vessel_cabin_group_slug')],
            },
        ),
        migrations.RunPython(publish_existing_vessels, migrations.RunPython.noop),
    ]
