# Generated by Django 5.2.17 on 2026-08-16 08:44

import catalog.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_vessel_content_backoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='card_image',
            field=models.ImageField(blank=True, storage=catalog.storage.build_media_storage, upload_to='vessels/cards/', verbose_name='卡片图'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='card_tone',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', '请输入 #071A32 形式的六位色值')], verbose_name='卡片底色'),
        ),
    ]
