# Generated by Django 5.2.17 on 2026-08-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_vessel_card_visuals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='ship_type',
        ),
        migrations.AddField(
            model_name='vessel',
            name='bar_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='酒吧数量'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='executive_lounge_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='行政酒廊'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='fitness_center_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='健身中心'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_science_center',
            field=models.BooleanField(default=False, verbose_name='科研中心'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_stabilization_system',
            field=models.BooleanField(default=False, verbose_name='船身稳定技术'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='无线网络'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='heated_pool_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='恒温泳池'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='infinity_pool_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='无边泳池'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='is_hybrid',
            field=models.BooleanField(default=False, verbose_name='混合动力'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='restaurant_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='餐厅数量'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='sauna_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='桑拿房'),
        ),
    ]
