# Generated by Django 5.2.17 on 2026-08-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_vessel_structured_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='executive_lounge_count',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='fitness_center_count',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='infinity_pool_count',
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_executive_lounge',
            field=models.BooleanField(default=False, verbose_name='行政酒廊'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_fitness_center',
            field=models.BooleanField(default=False, verbose_name='健身中心'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_infinity_pool',
            field=models.BooleanField(default=False, verbose_name='无边泳池'),
        ),
    ]
