# Generated by Django 5.2.17 on 2026-08-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_vessel_boolean_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='sauna_count',
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_sauna',
            field=models.BooleanField(default=False, verbose_name='桑拿房'),
        ),
    ]
