# Generated by Django 5.2.17 on 2026-08-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_vessel_boolean_sauna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='features',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='intro_en',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='short_pitch',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='source_url',
        ),
    ]
