# Generated by Django 5.2.17 on 2026-08-17 09:20

import catalog.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_vessel_unused_editorial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='show_cabins',
            field=models.BooleanField(default=True, verbose_name='展示舱位详情'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='show_deck_plans',
            field=models.BooleanField(default=False, verbose_name='展示甲板示意图'),
        ),
        migrations.CreateModel(
            name='VesselDeckPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='甲板名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('image', models.ImageField(storage=catalog.storage.build_media_storage, upload_to='vessels/deck-plans/', verbose_name='甲板示意图')),
                ('is_visible', models.BooleanField(default=True, verbose_name='展示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_plans', to='catalog.vessel', verbose_name='船只')),
            ],
            options={
                'verbose_name': '甲板示意图',
                'verbose_name_plural': '甲板示意图',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VesselPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', '分组标题'), ('card', '内容卡片')], max_length=16, verbose_name='项目类型')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('image', models.ImageField(blank=True, storage=catalog.storage.build_media_storage, upload_to='vessels/page-blocks/', verbose_name='图片')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('is_visible', models.BooleanField(default=True, verbose_name='展示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='catalog.vessel', verbose_name='船只')),
            ],
            options={
                'verbose_name': '船只页面内容',
                'verbose_name_plural': '船只页面内容',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
