# Generated by Django 5.2.17 on 2026-08-17 13:23

import catalog.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_vessel_page_composer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselPageBlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=catalog.storage.build_media_storage, upload_to='vessels/page-block-images/', verbose_name='附加图片')),
                ('is_visible', models.BooleanField(default=True, verbose_name='展示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('page_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='catalog.vesselpageblock', verbose_name='所属内容卡片')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_block_images', to='catalog.vessel', verbose_name='船只')),
            ],
            options={
                'verbose_name': '内容卡片附加图片',
                'verbose_name_plural': '内容卡片附加图片',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
