# Generated by Django 5.2.17 on 2026-08-21 04:09

import catalog.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_vesseldeckplan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='活动标题')),
                ('summary', models.TextField(blank=True, verbose_name='活动简介')),
                ('explanation', models.TextField(blank=True, verbose_name='解说文字')),
                ('hero_image', models.ImageField(blank=True, storage=catalog.storage.build_media_storage, upload_to='activities/heroes/', verbose_name='活动主图')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='发布状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='catalog.destination')),
                ('products', models.ManyToManyField(blank=True, related_name='activities', to='catalog.product')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=catalog.storage.build_media_storage, upload_to='activities/gallery/', verbose_name='活动图片')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='图片说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.activity')),
            ],
            options={
                'verbose_name': '活动图片',
                'verbose_name_plural': '活动图片',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
