# Generated by Django 5.2.17 on 2026-08-21 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_activity_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='catalog.destination'),
        ),
    ]
