# Generated by Django 5.2.17 on 2026-08-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_activity_destination_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['id'], 'verbose_name': '目的地', 'verbose_name_plural': '目的地'},
        ),
    ]
