# Generated by Django 5.2.17 on 2026-08-22 03:57

import catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_destination_remove_operations_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=catalog.storage.build_media_storage, unique=True, upload_to='assets/images/', verbose_name='素材图片')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='素材名称')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材库',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
