import { PlusOutlined } from "@ant-design/icons";
import { Button, Card, Image, Input, List, Modal, Space, Upload, message } from "antd";
import { useCallback, useEffect, useState } from "react";
import { listMediaAssets, updateMediaAsset, uploadMediaAsset, type MediaAsset } from "../../api/mediaAssets";

export function MediaAssetListPage() {
  const [items, setItems] = useState<MediaAsset[]>([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<MediaAsset | null>(null); const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(""); const [tags, setTags] = useState(""); const [saving, setSaving] = useState(false); const [messageApi, holder] = message.useMessage();
  const load = useCallback(async () => setItems((await listMediaAssets()).results), []); useEffect(() => { void load(); }, [load]);
  function close() { setOpen(false); setEditing(null); setFile(null); setTitle(""); setTags(""); }
  async function save() { if (!editing && !file) { messageApi.error("请先选择图片"); return; } const isEditing = Boolean(editing); setSaving(true); try { if (editing) await updateMediaAsset(editing.id, title, tags.split(",").map((tag) => tag.trim()).filter(Boolean)); else await uploadMediaAsset(file!, title, tags); close(); await load(); messageApi.success(isEditing ? "素材信息已更新" : "素材上传成功"); } catch { messageApi.error(isEditing ? "保存失败，请重试" : "上传失败，请重试"); } finally { setSaving(false); } }
  return <>{holder}<Card title="素材库" extra={<Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditing(null); setOpen(true); }}>上传素材</Button>}><List grid={{ gutter: 16, column: 4 }} dataSource={items} locale={{ emptyText: "暂时没有素材" }} renderItem={(asset) => <List.Item><Card cover={<Image preview={false} height={150} style={{ objectFit: "cover" }} src={asset.image} />} actions={[<Button type="link" onClick={() => { setEditing(asset); setTitle(asset.title); setTags(asset.tags.join(",")); setOpen(true); }}>编辑</Button>]}><Space direction="vertical" size={0}><strong>{asset.title || "未命名素材"}</strong><span>{asset.tags.join(" · ")}</span></Space></Card></List.Item>} /><Modal title={editing ? "编辑素材" : "上传素材"} open={open} onCancel={close} onOk={() => void save()} confirmLoading={saving} okText={editing ? "保存" : "上传素材"}><Space direction="vertical" style={{ width: "100%" }}><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="素材名称，默认使用文件名" /><Input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="标签，用逗号分隔" />{!editing && <Upload beforeUpload={(selected) => { setFile(selected); return false; }} maxCount={1}><Button>选择图片</Button></Upload>}</Space></Modal></Card></>;
}
