import { Button, Card, Form, Input, InputNumber, Select, Space, Spin, Tabs, message } from "antd";
import dayjs from "dayjs";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { listDestinations } from "../../api/destinations";
import { createProduct, getProduct, listVesselOptions, type Product, type ProductInput, updateProduct } from "../../api/products";
import { ItineraryEditor } from "./ItineraryEditor";
import { ProductDepartureEditor } from "./ProductDepartureEditor";
import { ProductImageEditor } from "./ProductImageEditor";

const splitLines = (value?: string[]) => (value ?? []).join("\n");
const toList = (value?: string) => (value ?? "").split("\n").map((item) => item.trim()).filter(Boolean);

export function ProductEditorPage() {
  const { id } = useParams(); const creating = id === "new"; const navigate = useNavigate(); const [form] = Form.useForm(); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [destinations, setDestinations] = useState<Array<{id:number; name:string}>>([]); const [vessels, setVessels] = useState<Array<{id:number; name:string}>>([]); const [product, setProduct] = useState<Product | null>(null); const [messageApi, holder] = message.useMessage();
  function populateForm(value: Product) { form.setFieldsValue({ ...value, tags_text: splitLines(value.tags), highlights_text: splitLines(value.highlights), included_text: splitLines(value.included), excluded_text: splitLines(value.excluded), suitable_for_text: splitLines(value.suitable_for), notices_text: splitLines(value.notices), departures: value.departures?.map((item) => ({...item, start_date: item.start_date ? dayjs(item.start_date) : undefined, end_date: item.end_date ? dayjs(item.end_date) : undefined})) }); }
  async function reloadProduct() { if (!creating && id) { const value = await getProduct(id); setProduct(value); populateForm(value); } }
  useEffect(() => { (async () => { try { const [destinationData, vesselData, loadedProduct] = await Promise.all([listDestinations(), listVesselOptions(), creating ? Promise.resolve(null) : getProduct(id!)]); setDestinations(destinationData.results); setVessels(vesselData.results); if (loadedProduct) { setProduct(loadedProduct); populateForm(loadedProduct); } } catch { messageApi.error("加载产品资料失败"); } finally { setLoading(false); } })(); }, [creating, form, id, messageApi]);
  async function save(values: Record<string, unknown>) { setSaving(true); try { const departures = ((values.departures as Array<Record<string, unknown>>) ?? []).map((item) => ({ label: String(item.label ?? ""), consultation_status: String(item.consultation_status ?? "可咨询"), vessel_id: item.vessel_id as number | null | undefined, start_date: item.start_date ? (item.start_date as dayjs.Dayjs).format("YYYY-MM-DD") : undefined, end_date: item.end_date ? (item.end_date as dayjs.Dayjs).format("YYYY-MM-DD") : undefined })); const payload: ProductInput = { title: String(values.title ?? ""), slug: String(values.slug ?? ""), subtitle: String(values.subtitle ?? ""), summary: String(values.summary ?? ""), season: String(values.season ?? ""), duration_days: values.duration_days as number | null | undefined, vessel: String(values.vessel ?? ""), departure_city: String(values.departure_city ?? ""), status: String(values.status ?? "draft"), sort_order: values.sort_order as number | undefined, destination_id: Number(values.destination_id), vessel_ids: values.vessel_ids as number[] | undefined, tags: toList(values.tags_text as string), highlights: toList(values.highlights_text as string), included: toList(values.included_text as string), excluded: toList(values.excluded_text as string), suitable_for: toList(values.suitable_for_text as string), notices: toList(values.notices_text as string), departures, itinerary_days: values.itinerary_days as ProductInput["itinerary_days"] }; if (creating) await createProduct(payload); else await updateProduct(Number(id), payload); messageApi.success("已保存"); navigate("/products"); } catch { messageApi.error("保存失败，请检查必填项和英文标识是否重复"); } finally { setSaving(false); } }
  if (loading) return <Spin />;
  return <>{holder}<Space style={{ marginBottom: 16 }}><Button onClick={() => navigate("/products")}>返回列表</Button><Button type="primary" loading={saving} onClick={() => form.submit()}>保存</Button></Space><Form form={form} layout="vertical" onFinish={(values) => void save(values)} initialValues={{ status: "draft", vessel_ids: [], departures: [], itinerary_days: [] }}><Tabs items={[
    { key:"basic", label:"基础信息", children:<Card><Form.Item label="产品名称" name="title" rules={[{required:true}]}><Input /></Form.Item><Form.Item label="英文标识" name="slug" rules={[{required:true}]}><Input /></Form.Item><Form.Item label="目的地" name="destination_id" rules={[{required:true}]}><Select options={destinations.map(d=>({value:d.id,label:d.name}))}/></Form.Item><Form.Item label="关联船只" name="vessel_ids"><Select mode="multiple" options={vessels.map(v=>({value:v.id,label:v.name}))}/></Form.Item><Form.Item label="发布状态" name="status"><Select options={[{value:"draft",label:"草稿"},{value:"published",label:"已发布"},{value:"archived",label:"已下架"}]}/></Form.Item><Form.Item label="行程天数" name="duration_days"><InputNumber min={1}/></Form.Item><Form.Item label="航季" name="season"><Input /></Form.Item><Form.Item label="副标题" name="subtitle"><Input /></Form.Item><Form.Item label="产品简介" name="summary"><Input.TextArea rows={4}/></Form.Item></Card> },
    { key:"departure", label:"团期", children:<Card><ProductDepartureEditor vessels={vessels}/></Card> }, { key:"itinerary", label:"每日行程", children:<Card><ItineraryEditor/></Card> },
    ...(!creating && product ? [{ key:"images", label:"图片", children:<ProductImageEditor product={product} onChanged={reloadProduct} /> }] : []),
    { key:"details", label:"亮点与费用", children:<Card><Form.Item label="标签（每行一项）" name="tags_text"><Input.TextArea rows={3}/></Form.Item><Form.Item label="产品亮点（每行一项）" name="highlights_text"><Input.TextArea rows={4}/></Form.Item><Form.Item label="费用包含（每行一项）" name="included_text"><Input.TextArea rows={4}/></Form.Item><Form.Item label="费用不含（每行一项）" name="excluded_text"><Input.TextArea rows={4}/></Form.Item><Form.Item label="适合人群（每行一项）" name="suitable_for_text"><Input.TextArea rows={3}/></Form.Item><Form.Item label="重要提醒（每行一项）" name="notices_text"><Input.TextArea rows={3}/></Form.Item></Card> }
  ]}/></Form></>;
}
