import { Button, Card, Form, Image, Input, List, Popconfirm, Select, Space, Spin, Upload } from "antd";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { createActivity, deleteActivityImage, getActivity, updateActivity, uploadActivityHero, uploadActivityImage, type Activity, type ActivityInput } from "../../api/activities";
import { listDestinations } from "../../api/destinations";
import { listProducts } from "../../api/products";

export function ActivityEditorPage() {
  const { id } = useParams(); const creating=id==="new"; const [form]=Form.useForm<ActivityInput>(); const [item,setItem]=useState<Activity|null>(null); const [loading,setLoading]=useState(true); const navigate=useNavigate(); const [alt,setAlt]=useState("");
  async function load(){ const [destinations,products,current]=await Promise.all([listDestinations(),listProducts(),creating?Promise.resolve(null):getActivity(id!)]); setOptions({destinations:destinations.results,products:products.results}); if(current){setItem(current);form.setFieldsValue(current);} setLoading(false); }
  const [options,setOptions]=useState<{destinations:Array<{id:number;name:string}>;products:Array<{id:number;title:string}>}>({destinations:[],products:[]}); useEffect(()=>{void load();},[id]);
  async function save(values:ActivityInput){ if(creating) await createActivity(values); else await updateActivity(Number(id),values); navigate("/activities"); }
  async function refresh(){ if(!creating&&id){const current=await getActivity(id);setItem(current);form.setFieldsValue(current);} }
  if(loading)return <Spin/>; return <><Space style={{marginBottom:16}}><Button onClick={()=>navigate("/activities")}>返回列表</Button><Button type="primary" onClick={()=>form.submit()}>保存</Button></Space><Form form={form} layout="vertical" onFinish={(v)=>void save(v)} initialValues={{status:"draft",product_ids:[]}}><Card title="基础信息"><Form.Item label="标题" name="title" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="目的地" name="destination_id" rules={[{required:true}]}><Select options={options.destinations.map(x=>({value:x.id,label:x.name}))}/></Form.Item><Form.Item label="关联旅行产品" name="product_ids"><Select mode="multiple" options={options.products.map(x=>({value:x.id,label:x.title}))}/></Form.Item><Form.Item label="活动简介" name="summary"><Input.TextArea rows={4}/></Form.Item><Form.Item label="解说文字" name="explanation"><Input.TextArea rows={4}/></Form.Item><Form.Item label="状态" name="status"><Select options={[{value:"draft",label:"草稿"},{value:"published",label:"已发布"}]}/></Form.Item></Card><Card title="活动图片" style={{marginTop:16}}>{creating?<>请先保存基础信息，再上传活动图片。</>:<>{item?.hero_image&&<Image width={200} src={item.hero_image}/>}<Upload showUploadList={false} beforeUpload={()=>false} onChange={({file})=>file.originFileObj&&void uploadActivityHero(item!.id,file.originFileObj).then(refresh)}><Button>上传活动主图</Button></Upload><Input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="图片说明（可选）" style={{marginTop:16}}/><Upload showUploadList={false} beforeUpload={()=>false} onChange={({file})=>file.originFileObj&&void uploadActivityImage(item!.id,file.originFileObj,alt).then(refresh)}><Button style={{marginTop:8}}>添加图库图片</Button></Upload><List dataSource={item?.images??[]} renderItem={image=><List.Item actions={[<Popconfirm title="删除这张图片？" onConfirm={()=>void deleteActivityImage(item!.id,image.id).then(refresh)}><Button danger type="link">删除</Button></Popconfirm>]}><Image width={120} src={image.image}/><span>{image.alt_text}</span></List.Item>}/></>}</Card></Form></>;
}
