import { DeleteOutlined, EditOutlined, PlusOutlined } from "@ant-design/icons";
import { Button, Checkbox, Form, Image, Input, InputNumber, List, Modal, Popconfirm, Select, Space, Tabs, message } from "antd";
import { useCallback, useEffect, useState } from "react";
import { createCabin, createCabinGroup, deleteCabin, listCabinGroups, listCabins, updateCabin, useCabinMediaAsset, type Cabin, type CabinGroup } from "../../api/vessels";
import { MediaAssetPicker } from "../../components/MediaAssetPicker";

type CabinValues = Omit<Partial<Cabin>, "id" | "image" | "sort_order">;
const lineList = (value?: string[]) => (value ?? []).join("\n");
const parseLines = (value?: string) => (value ?? "").split("\n").map((item) => item.trim()).filter(Boolean);

export function CabinEditor({ vesselId }: { vesselId: number }) {
  const [cabins, setCabins] = useState<Cabin[]>([]); const [groups, setGroups] = useState<CabinGroup[]>([]); const [editing, setEditing] = useState<Cabin | null>(null); const [open, setOpen] = useState(false); const [form] = Form.useForm(); const [groupForm] = Form.useForm(); const [groupOpen, setGroupOpen] = useState(false); const [messageApi, holder] = message.useMessage();
  const load = useCallback(async () => { try { const [cabinData, groupData] = await Promise.all([listCabins(vesselId), listCabinGroups(vesselId)]); setCabins(cabinData.results); setGroups(groupData.results); } catch { messageApi.error("加载舱位资料失败"); } }, [messageApi, vesselId]);
  useEffect(() => { void load(); }, [load]);
  function openCabin(cabin?: Cabin) { setEditing(cabin ?? null); form.setFieldsValue(cabin ? { ...cabin, amenities_text: lineList(cabin.amenities), display_tags_text: lineList(cabin.display_tags), highlights_text: lineList(cabin.highlights) } : { is_visible: true, is_accessible: false }); setOpen(true); }
  async function save(values: Record<string, unknown>) { const data: CabinValues = { ...values, amenities: parseLines(values.amenities_text as string), display_tags: parseLines(values.display_tags_text as string), highlights: parseLines(values.highlights_text as string) }; try { if (editing) await updateCabin(vesselId, editing.id, data); else await createCabin(vesselId, data); setOpen(false); await load(); messageApi.success("已保存"); } catch { messageApi.error("保存失败"); } }
  async function remove(cabin: Cabin) { try { await deleteCabin(vesselId, cabin.id); await load(); messageApi.success("已删除"); } catch { messageApi.error("删除失败"); } }
  async function selectImage(cabinId: number, assetId: number) { try { await useCabinMediaAsset(vesselId, cabinId, assetId); await load(); messageApi.success("已使用素材库图片"); } catch { messageApi.error("素材图片设置失败"); } }
  async function saveGroup(values: CabinGroup) { try { await createCabinGroup(vesselId, values); setGroupOpen(false); await load(); messageApi.success("分组已创建"); } catch { messageApi.error("分组保存失败"); } }
  return <>{holder}<Tabs items={[{ key: "cabins", label: "舱位", children: <><Button type="primary" icon={<PlusOutlined />} onClick={() => openCabin()} style={{ marginBottom: 16 }}>添加舱位</Button><List bordered dataSource={cabins} locale={{ emptyText: "暂无舱位" }} renderItem={(item) => <List.Item actions={[<Button key="edit" type="link" icon={<EditOutlined />} onClick={() => openCabin(item)}>编辑</Button>, <Popconfirm key="delete" title="确定删除这个舱位？" onConfirm={() => void remove(item)}><Button type="link" danger icon={<DeleteOutlined />}>删除</Button></Popconfirm>]}><Space>{item.image ? <Image width={100} height={66} style={{ objectFit: "cover" }} src={item.image} alt={item.name} /> : <span>无图片</span>}<span><strong>{item.name}</strong><br />{item.category || "未分类"} · {item.size_sqm ? `${item.size_sqm}㎡` : "面积待补充"}</span><MediaAssetPicker onSelect={(asset) => void selectImage(item.id, asset.id)} /></Space></List.Item>} /></> }, { key: "groups", label: "舱位展示分组", children: <><Button type="primary" icon={<PlusOutlined />} onClick={() => { groupForm.resetFields(); setGroupOpen(true); }} style={{ marginBottom: 16 }}>添加分组</Button><List bordered dataSource={groups} locale={{ emptyText: "暂无展示分组" }} renderItem={(item) => <List.Item><strong>{item.title_zh}</strong>&nbsp;（{item.cabin_ids.length} 个舱位）</List.Item>} /></> }]} />
    <Modal title={editing ? "编辑舱位" : "添加舱位"} open={open} onCancel={() => setOpen(false)} onOk={() => form.submit()} width={760} destroyOnHidden><Form form={form} layout="vertical" onFinish={(values) => void save(values)}><Space direction="vertical" style={{ width: "100%" }} size={0}><Form.Item label="舱位名称" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="官方代码" name="official_code"><Input /></Form.Item><Form.Item label="分类" name="category"><Input /></Form.Item><Form.Item label="面积（㎡）" name="size_sqm"><InputNumber min={0} /></Form.Item><Form.Item label="最多入住人数" name="max_guests"><InputNumber min={1} /></Form.Item><Form.Item label="甲板" name="deck"><Input /></Form.Item><Form.Item label="中文简介" name="summary"><Input.TextArea rows={3} /></Form.Item><Form.Item label="中文完整介绍" name="description_zh"><Input.TextArea rows={4} /></Form.Item><Form.Item label="展示标签（每行一项）" name="display_tags_text"><Input.TextArea rows={3} /></Form.Item><Form.Item label="设施（每行一项）" name="amenities_text"><Input.TextArea rows={3} /></Form.Item><Form.Item name="is_visible" valuePropName="checked"><Checkbox>展示此舱位</Checkbox></Form.Item><Form.Item name="is_accessible" valuePropName="checked"><Checkbox>无障碍舱位</Checkbox></Form.Item></Space></Form></Modal>
    <Modal title="添加舱位展示分组" open={groupOpen} onCancel={() => setGroupOpen(false)} onOk={() => groupForm.submit()} destroyOnHidden><Form form={groupForm} layout="vertical" onFinish={(values) => void saveGroup(values)}><Form.Item label="中文分组名称" name="title_zh" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="英文标识" name="slug" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="包含舱位" name="cabin_ids"><Select mode="multiple" options={cabins.map((cabin) => ({ value: cabin.id, label: cabin.name }))} /></Form.Item></Form></Modal></>;
}
