import { DeleteOutlined, DownOutlined, EditOutlined, PlusOutlined, UpOutlined } from "@ant-design/icons";
import { Button, Form, Image, Input, List, Modal, Popconfirm, Space, Tag, Upload, message } from "antd";
import type { UploadProps } from "antd";
import { useCallback, useEffect, useState } from "react";
import {
  createVesselPageBlock, deleteVesselPageBlock, deleteVesselPageBlockImage, listVesselPageBlocks, reorderVesselPageBlocks,
  updateVesselPageBlock, uploadVesselPageBlockImage, type VesselPageBlock,
} from "../../api/vessels";

type BlockValues = { block_type: "heading" | "card"; title: string; body?: string };
const selectOnly: UploadProps["beforeUpload"] = () => false;

export function PageBlockEditor({ vesselId }: { vesselId: number }) {
  const [items, setItems] = useState<VesselPageBlock[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<VesselPageBlock | null>(null); const [file, setFile] = useState<File | null>(null); const [form] = Form.useForm<BlockValues>(); const [messageApi, holder] = message.useMessage();
  const load = useCallback(async () => { setLoading(true); try { setItems((await listVesselPageBlocks(vesselId)).results); } catch { messageApi.error("加载页面内容失败"); } finally { setLoading(false); } }, [messageApi, vesselId]);
  useEffect(() => { void load(); }, [load]);
  function openCreate(blockType: "heading" | "card") { setEditing(null); setFile(null); form.setFieldsValue({ block_type: blockType, title: "", body: "" }); setOpen(true); }
  function openEdit(item: VesselPageBlock) { setEditing(item); setFile(null); form.setFieldsValue({ block_type: item.block_type, title: item.title, body: item.body }); setOpen(true); }
  async function save(values: BlockValues) { const input = { ...values, body: values.body ?? "" }; try { if (editing) await updateVesselPageBlock(vesselId, editing.id, input); else { if (values.block_type === "card" && !file) { messageApi.error("内容卡片必须选择图片"); return; } await createVesselPageBlock(vesselId, input, file ?? undefined); } setOpen(false); await load(); messageApi.success("已保存"); } catch { messageApi.error("保存失败"); } }
  async function remove(item: VesselPageBlock) { try { await deleteVesselPageBlock(vesselId, item.id); await load(); messageApi.success("已删除"); } catch { messageApi.error("删除失败"); } }
  async function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= items.length) return; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; try { await reorderVesselPageBlocks(vesselId, next.map((item) => item.id)); setItems(next); } catch { messageApi.error("排序失败"); } }
  async function addExtra(blockId: number, image: File) { try { await uploadVesselPageBlockImage(vesselId, blockId, image); await load(); messageApi.success("图片已添加"); } catch { messageApi.error("图片上传失败"); } }
  async function removeExtra(blockId: number, imageId: number) { try { await deleteVesselPageBlockImage(vesselId, blockId, imageId); await load(); } catch { messageApi.error("图片删除失败"); } }
  return <>{holder}<Space style={{ marginBottom: 16 }}><Button icon={<PlusOutlined />} onClick={() => openCreate("heading")}>添加分组标题</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => openCreate("card")}>添加内容卡片</Button></Space><List loading={loading} bordered dataSource={items} locale={{ emptyText: "暂未配置页面内容" }} renderItem={(item, index) => <List.Item actions={[<Button key="up" type="link" icon={<UpOutlined />} disabled={index === 0} onClick={() => void move(index, -1)}>上移</Button>, <Button key="down" type="link" icon={<DownOutlined />} disabled={index === items.length - 1} onClick={() => void move(index, 1)}>下移</Button>, <Button key="edit" type="link" icon={<EditOutlined />} onClick={() => openEdit(item)}>编辑</Button>, <Popconfirm key="delete" title="确定删除这项内容？" onConfirm={() => void remove(item)}><Button type="link" danger icon={<DeleteOutlined />}>删除</Button></Popconfirm>]}><Space direction="vertical" size={8} style={{ width: "100%" }}><Space><Tag color={item.block_type === "heading" ? "blue" : "green"}>{item.block_type === "heading" ? "标题" : "卡片"}</Tag><strong>{item.title}</strong></Space>{item.block_type === "card" && <><Space wrap>{item.image && <Image width={120} height={80} style={{ objectFit: "cover" }} src={item.image} alt={item.title} />}{item.additional_images.map((image) => <Space key={image.id} direction="vertical" size={0}><Image width={80} height={54} style={{ objectFit: "cover" }} src={image.image} alt={item.title} /><Popconfirm title="删除这张额外图片？" onConfirm={() => void removeExtra(item.id, image.id)}><Button danger type="link" size="small">删除</Button></Popconfirm></Space>)}</Space><Upload accept="image/*" showUploadList={false} beforeUpload={selectOnly} onChange={({ file }) => file.originFileObj && void addExtra(item.id, file.originFileObj)}><Button size="small">添加额外图片</Button></Upload>{item.body && <span>{item.body}</span>}</>}</Space></List.Item>} />
    <Modal title={editing ? "编辑页面内容" : "添加页面内容"} open={open} onCancel={() => setOpen(false)} onOk={() => form.submit()} destroyOnHidden><Form form={form} layout="vertical" onFinish={(values) => void save(values)}><Form.Item name="block_type" hidden><Input /></Form.Item><Form.Item label="类型"><Input value={form.getFieldValue("block_type") === "heading" ? "分组标题" : "内容卡片"} disabled /></Form.Item><Form.Item label="标题" name="title" rules={[{ required: true, message: "请输入标题" }]}><Input /></Form.Item><Form.Item noStyle shouldUpdate={(prev, current) => prev.block_type !== current.block_type}>{({ getFieldValue }) => getFieldValue("block_type") === "card" && <><Form.Item label="正文" name="body"><Input.TextArea rows={5} /></Form.Item>{!editing && <Form.Item label="图片" required><Upload accept="image/*" maxCount={1} beforeUpload={selectOnly} onChange={({ file }) => setFile(file.originFileObj ?? null)}><Button>选择图片</Button></Upload></Form.Item>}</>}</Form.Item></Form></Modal></>;
}
